--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Abi2005/NpcForm
build-by-default: true
branches:
- master
projects:
  NpcForm:
    path: ""
    model: virion
    type: library
...

